"""Tests for cl.sync.mappers — the per-model Django ORM save functions.

Each mapper is tested with three paths:
  1. First sync, object does NOT exist  → create new
  2. First sync, object DOES exist      → find by natural key, update
  3. Subsequent sync (courtlistener_id)  → find by PK, update

StubDocketCreationTest verifies that dependent mappers create stub dockets
when the parent docket hasn't been synced yet, and that those stubs are
later updated by ``sync_docket``.
"""

from datetime import date
from unittest.mock import MagicMock, patch

from cl.audio.factories import AudioWithParentsFactory
from cl.audio.models import Audio
from cl.search.docket_sources import DocketSources
from cl.search.factories import (
    CourtFactory,
    DocketEntryFactory,
    DocketFactory,
    OpinionClusterWithParentsFactory,
    OpinionFactory,
)
from cl.search.models import (
    Docket,
    DocketEntry,
    Opinion,
    OpinionCluster,
    OriginatingCourtInformation,
    SOURCES,
)
from cl.sync.mappers import (
    sync_audio,
    sync_docket,
    sync_docket_entry,
    sync_opinion,
    sync_opinion_cluster,
    sync_originating_court_information,
)
from cl.tests.cases import TestCase


class SyncDocketTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsyncd", jurisdiction="SA")

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-0001",
            "case_name": "Smith v. Jones",
            "case_name_short": "Smith",
            "case_name_full": "John Smith v. Bob Jones",
            "date_filed": date(2024, 1, 15),
            "cause": "Civil",
            "nature_of_suit": "",
            "assigned_to_str": "",
            "referred_to_str": "",
            "panel_str": "",
            "appeal_from_str": "Circuit Court",
            "blocked": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_docket(self):
        row = self._make_row()
        cl_id = sync_docket(row)

        docket = Docket.objects.get(pk=cl_id)
        self.assertEqual(docket.court_id, self.court.id)
        self.assertEqual(docket.docket_number, "SC-2024-0001")
        self.assertEqual(docket.case_name, "Smith v. Jones")
        self.assertEqual(docket.appeal_from_str, "Circuit Court")
        self.assertEqual(docket.source, DocketSources.SCRAPER)
        # slug is auto-generated by Docket.save()
        self.assertTrue(docket.slug)

    def test_finds_existing_by_natural_key(self):
        existing = DocketFactory(
            court=self.court,
            docket_number="SC-2024-0001",
            source=DocketSources.DEFAULT,
            case_name="Old Name",
        )

        row = self._make_row()
        cl_id = sync_docket(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Smith v. Jones")
        # Source is merged: DEFAULT (0) + SCRAPER (2) = SCRAPER (2)
        self.assertEqual(existing.source, DocketSources.SCRAPER)

    def test_updates_by_courtlistener_id(self):
        existing = DocketFactory(
            court=self.court,
            docket_number="SC-2024-0001",
            source=DocketSources.SCRAPER,
            case_name="Old Name",
        )

        row = self._make_row(
            courtlistener_id=existing.pk,
            case_name="Updated Name",
        )
        cl_id = sync_docket(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Updated Name")

    def test_null_fields_do_not_overwrite(self):
        existing = DocketFactory(
            court=self.court,
            docket_number="SC-2024-0002",
            source=DocketSources.SCRAPER,
            cause="Original Cause",
        )

        row = self._make_row(
            docket_number="SC-2024-0002",
            courtlistener_id=existing.pk,
            cause=None,  # NULL — should not overwrite
        )
        sync_docket(row)
        existing.refresh_from_db()
        self.assertEqual(existing.cause, "Original Cause")

    def test_merges_source_with_existing(self):
        existing = DocketFactory(
            court=self.court,
            docket_number="SC-2024-0003",
            source=DocketSources.COLUMBIA,  # 4
        )

        row = self._make_row(docket_number="SC-2024-0003")
        sync_docket(row)
        existing.refresh_from_db()
        # COLUMBIA (4) merged with SCRAPER (2) = COLUMBIA_AND_SCRAPER (6)
        expected = DocketSources.merge_sources(
            DocketSources.COLUMBIA, DocketSources.SCRAPER
        )
        self.assertEqual(existing.source, expected)

    def test_date_filed_as_string(self):
        row = self._make_row(
            docket_number="SC-2024-0004",
            date_filed="2024-06-15",
        )
        cl_id = sync_docket(row)
        docket = Docket.objects.get(pk=cl_id)
        self.assertEqual(docket.date_filed, date(2024, 6, 15))


class SyncOriginatingCourtInformationTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsyncoci", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-OCI",
            source=DocketSources.SCRAPER,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-OCI",
            "lower_court_docket_number": "CV-2023-001",
            "court_reporter": "Jane Reporter",
            "assigned_to_str": "Judge Smith",
            "ordering_judge_str": "Judge Order",
            "date_filed": date(2023, 5, 1),
            "date_disposed": date(2023, 12, 1),
            "date_judgment": None,
            "date_judgment_eod": None,
            "date_filed_noa": None,
            "date_received_coa": None,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_oci(self):
        row = self._make_row()
        cl_id = sync_originating_court_information(row)

        oci = OriginatingCourtInformation.objects.get(pk=cl_id)
        self.assertEqual(oci.docket_number, "CV-2023-001")
        self.assertEqual(oci.court_reporter, "Jane Reporter")
        self.assertEqual(oci.date_filed, date(2023, 5, 1))

        # Docket should now reference this OCI
        self.docket.refresh_from_db()
        self.assertEqual(self.docket.originating_court_information_id, cl_id)

    def test_updates_existing_oci(self):
        oci = OriginatingCourtInformation.objects.create(
            docket_number="Old Number"
        )
        self.docket.originating_court_information = oci
        self.docket.save()

        row = self._make_row()
        cl_id = sync_originating_court_information(row)

        self.assertEqual(cl_id, oci.pk)
        oci.refresh_from_db()
        self.assertEqual(oci.docket_number, "CV-2023-001")

    def test_updates_by_courtlistener_id(self):
        oci = OriginatingCourtInformation.objects.create(
            docket_number="Old Number"
        )
        self.docket.originating_court_information = oci
        self.docket.save()

        row = self._make_row(
            courtlistener_id=oci.pk,
            court_reporter="New Reporter",
        )
        cl_id = sync_originating_court_information(row)

        self.assertEqual(cl_id, oci.pk)
        oci.refresh_from_db()
        self.assertEqual(oci.court_reporter, "New Reporter")


class SyncOpinionClusterTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsyncoc", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-OC",
            source=DocketSources.SCRAPER,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-OC",
            "date_filed": date(2024, 3, 15),
            "case_name": "Doe v. State",
            "case_name_short": "Doe",
            "case_name_full": "Jane Doe v. State of Alabama",
            "judges": "Robinson, C.J.",
            "precedential_status": "Published",
            "syllabus": "Test syllabus",
            "headnotes": "",
            "summary": "",
            "disposition": "Affirmed",
            "procedural_history": "",
            "attorneys": "Smith, Esq.",
            "blocked": False,
            "date_filed_is_approximate": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_cluster(self):
        row = self._make_row()
        cl_id = sync_opinion_cluster(row)

        cluster = OpinionCluster.objects.get(pk=cl_id)
        self.assertEqual(cluster.docket_id, self.docket.pk)
        self.assertEqual(cluster.date_filed, date(2024, 3, 15))
        self.assertEqual(cluster.case_name, "Doe v. State")
        self.assertEqual(cluster.judges, "Robinson, C.J.")
        self.assertEqual(cluster.disposition, "Affirmed")

    def test_finds_existing_by_natural_key(self):
        existing = OpinionCluster.objects.create(
            docket=self.docket,
            date_filed=date(2024, 3, 15),
            case_name="Old Name",
            source=SOURCES.COURT_WEBSITE,
        )

        row = self._make_row()
        cl_id = sync_opinion_cluster(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Doe v. State")

    def test_updates_by_courtlistener_id(self):
        existing = OpinionCluster.objects.create(
            docket=self.docket,
            date_filed=date(2024, 3, 15),
            case_name="Old Name",
            source=SOURCES.COURT_WEBSITE,
        )

        row = self._make_row(
            courtlistener_id=existing.pk,
            case_name="Updated Name",
        )
        cl_id = sync_opinion_cluster(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Updated Name")


class SyncOpinionTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsynco", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-OP",
            source=DocketSources.SCRAPER,
        )
        cls.cluster = OpinionCluster.objects.create(
            docket=cls.docket,
            date_filed=date(2024, 4, 1),
            case_name="Test Case",
            source=SOURCES.COURT_WEBSITE,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-OP",
            "cluster_date_filed": date(2024, 4, 1),
            "type": Opinion.LEAD,
            "author_str": "Judge Smith",
            "per_curiam": False,
            "joined_by_str": "",
            "sha1": "abc123",
            "page_count": 10,
            "download_url": "https://example.com/opinion.pdf",
            "plain_text": "Opinion text here.",
            "html": "",
            "extracted_by_ocr": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_opinion(self):
        row = self._make_row()
        cl_id = sync_opinion(row)

        opinion = Opinion.objects.get(pk=cl_id)
        self.assertEqual(opinion.cluster_id, self.cluster.pk)
        self.assertEqual(opinion.type, Opinion.LEAD)
        self.assertEqual(opinion.author_str, "Judge Smith")
        self.assertEqual(opinion.plain_text, "Opinion text here.")
        self.assertEqual(opinion.sha1, "abc123")

    def test_finds_existing_by_natural_key(self):
        existing = Opinion.objects.create(
            cluster=self.cluster,
            type=Opinion.LEAD,
            author_str="Judge Smith",
            sha1="old_sha",
        )

        row = self._make_row()
        cl_id = sync_opinion(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.sha1, "abc123")
        self.assertEqual(existing.plain_text, "Opinion text here.")

    def test_updates_by_courtlistener_id(self):
        existing = Opinion.objects.create(
            cluster=self.cluster,
            type=Opinion.LEAD,
            author_str="Judge Smith",
            sha1="old_sha",
        )

        row = self._make_row(
            courtlistener_id=existing.pk,
            plain_text="Updated text.",
        )
        cl_id = sync_opinion(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.plain_text, "Updated text.")


class SyncOpinionFileTest(TestCase):
    """Tests that sync_opinion copies PDFs from the scraper S3 bucket
    into CL's media storage via opinion.local_path.
    """

    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsyncof", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-FILE",
            source=DocketSources.SCRAPER,
        )
        cls.cluster = OpinionCluster.objects.create(
            docket=cls.docket,
            date_filed=date(2024, 4, 1),
            case_name="File Test Case",
            source=SOURCES.COURT_WEBSITE,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-FILE",
            "cluster_date_filed": date(2024, 4, 1),
            "type": Opinion.LEAD,
            "author_str": "Judge File",
            "per_curiam": False,
            "joined_by_str": "",
            "sha1": "filesha",
            "page_count": 5,
            "download_url": "https://example.com/file-opinion.pdf",
            "plain_text": "",
            "html": "",
            "extracted_by_ocr": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    @patch("cl.sync.mappers._get_scraper_s3_client")
    def test_copies_s3_file_to_local_path(self, mock_get_client):
        mock_body = MagicMock()
        mock_body.read.return_value = b"%PDF-1.4 fake pdf content"
        mock_client = MagicMock()
        mock_client.get_object.return_value = {"Body": mock_body}
        mock_get_client.return_value = mock_client

        row = self._make_row(
            local_path="s3://scrapers/ala_publicportal/files/test-uuid.pdf",
        )
        cl_id = sync_opinion(row)

        opinion = Opinion.objects.get(pk=cl_id)
        self.assertTrue(opinion.local_path)
        self.assertIn("pdf/2024/04/01/", opinion.local_path.name)
        mock_client.get_object.assert_called_once_with(
            Bucket="scrapers",
            Key="ala_publicportal/files/test-uuid.pdf",
        )

    @patch("cl.sync.mappers._get_scraper_s3_client")
    def test_skips_copy_when_no_local_path(self, mock_get_client):
        row = self._make_row(
            author_str="Judge NoFile",
            local_path=None,
        )
        cl_id = sync_opinion(row)

        opinion = Opinion.objects.get(pk=cl_id)
        self.assertFalse(opinion.local_path)
        mock_get_client.assert_not_called()

    @patch("cl.sync.mappers._get_scraper_s3_client")
    def test_skips_copy_when_local_path_not_s3(self, mock_get_client):
        row = self._make_row(
            author_str="Judge LocalPath",
            local_path="/some/local/path.pdf",
        )
        cl_id = sync_opinion(row)

        opinion = Opinion.objects.get(pk=cl_id)
        self.assertFalse(opinion.local_path)
        mock_get_client.assert_not_called()


class SyncDocketEntryTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsyncde", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-DE",
            source=DocketSources.SCRAPER,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-DE",
            "document_uuid": "uuid-001",
            "date_filed": date(2024, 5, 1),
            "time_filed": None,
            "entry_number": 1,
            "description": "Complaint filed",
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_docket_entry(self):
        row = self._make_row()
        cl_id = sync_docket_entry(row)

        de = DocketEntry.objects.get(pk=cl_id)
        self.assertEqual(de.docket_id, self.docket.pk)
        self.assertEqual(de.entry_number, 1)
        self.assertEqual(de.description, "Complaint filed")
        self.assertEqual(de.date_filed, date(2024, 5, 1))

    def test_finds_existing_by_entry_number(self):
        existing = DocketEntry.objects.create(
            docket=self.docket,
            entry_number=1,
            description="Old description",
        )

        row = self._make_row()
        cl_id = sync_docket_entry(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.description, "Complaint filed")

    def test_updates_by_courtlistener_id(self):
        existing = DocketEntry.objects.create(
            docket=self.docket,
            entry_number=1,
            description="Old",
        )

        row = self._make_row(
            courtlistener_id=existing.pk,
            description="Updated description",
        )
        cl_id = sync_docket_entry(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.description, "Updated description")

    def test_creates_new_when_no_entry_number(self):
        row = self._make_row(entry_number=None)
        cl_id = sync_docket_entry(row)

        de = DocketEntry.objects.get(pk=cl_id)
        self.assertEqual(de.docket_id, self.docket.pk)
        self.assertIsNone(de.entry_number)
        self.assertEqual(de.description, "Complaint filed")


class SyncAudioTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="testsynca", jurisdiction="SA")
        cls.docket = DocketFactory(
            court=cls.court,
            docket_number="SC-2024-AU",
            source=DocketSources.SCRAPER,
        )

    def _make_row(self, **overrides):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-2024-AU",
            "date_argued": date(2024, 6, 1),
            "case_name": "Audio Case",
            "case_name_short": "Audio",
            "case_name_full": "Audio Case Full Name",
            "judges": "Panel Judge A",
            "source": SOURCES.COURT_WEBSITE,
            "download_url": "https://example.com/audio.mp3",
            "duration": 3600,
            "stt_status": Audio.STT_NEEDED,
            "blocked": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    def test_creates_new_audio(self):
        row = self._make_row()
        cl_id = sync_audio(row)

        audio = Audio.objects.get(pk=cl_id)
        self.assertEqual(audio.docket_id, self.docket.pk)
        self.assertEqual(audio.case_name, "Audio Case")
        self.assertEqual(audio.download_url, "https://example.com/audio.mp3")
        self.assertEqual(audio.duration, 3600)

    def test_finds_existing_by_download_url(self):
        existing = Audio.objects.create(
            docket=self.docket,
            case_name="Old Name",
            download_url="https://example.com/audio.mp3",
            sha1="abc",
        )

        row = self._make_row()
        cl_id = sync_audio(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Audio Case")
        self.assertEqual(existing.duration, 3600)

    def test_updates_by_courtlistener_id(self):
        existing = Audio.objects.create(
            docket=self.docket,
            case_name="Old Name",
            download_url="https://example.com/audio.mp3",
            sha1="abc",
        )

        row = self._make_row(
            courtlistener_id=existing.pk,
            case_name="Updated Audio Case",
        )
        cl_id = sync_audio(row)

        self.assertEqual(cl_id, existing.pk)
        existing.refresh_from_db()
        self.assertEqual(existing.case_name, "Updated Audio Case")

    def test_creates_new_when_no_download_url(self):
        row = self._make_row(download_url=None)
        cl_id = sync_audio(row)

        audio = Audio.objects.get(pk=cl_id)
        self.assertEqual(audio.docket_id, self.docket.pk)
        self.assertEqual(audio.case_name, "Audio Case")


class StubDocketCreationTest(TestCase):
    """Tests that dependent mappers create stub dockets when the parent
    docket hasn't been synced yet, and that sync_docket later updates
    the stub with full data.
    """

    @classmethod
    def setUpTestData(cls):
        cls.court = CourtFactory(id="teststub", jurisdiction="SA")

    def _full_docket_row(self, docket_number, **overrides):
        """A complete docket row as sync_docket would receive."""
        row = {
            "court_id": self.court.id,
            "docket_number": docket_number,
            "case_name": "Full Case Name",
            "case_name_short": "Full",
            "case_name_full": "Full Case Name v. State",
            "date_filed": date(2024, 1, 15),
            "cause": "Appeal",
            "nature_of_suit": "",
            "assigned_to_str": "",
            "referred_to_str": "",
            "panel_str": "Robinson, C.J.",
            "appeal_from_str": "Circuit Court",
            "blocked": False,
            "courtlistener_id": None,
        }
        row.update(overrides)
        return row

    # -- opinion_cluster -------------------------------------------------------

    def test_opinion_cluster_creates_stub_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OC",
            "date_filed": date(2024, 3, 15),
            "case_name": "Stub v. State",
            "case_name_short": "Stub",
            "case_name_full": "",
            "judges": "",
            "precedential_status": "Published",
            "syllabus": "",
            "headnotes": "",
            "summary": "",
            "disposition": "",
            "procedural_history": "",
            "attorneys": "",
            "blocked": False,
            "date_filed_is_approximate": False,
            "courtlistener_id": None,
        }
        cl_id = sync_opinion_cluster(row)

        cluster = OpinionCluster.objects.get(pk=cl_id)
        stub = cluster.docket
        self.assertEqual(stub.court_id, self.court.id)
        self.assertEqual(stub.docket_number, "SC-STUB-OC")
        self.assertEqual(stub.source, DocketSources.SCRAPER)
        self.assertEqual(stub.case_name, "Stub v. State")

    def test_opinion_cluster_stub_updated_by_sync_docket(self):
        # Create stub via opinion cluster sync
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OC2",
            "date_filed": date(2024, 3, 15),
            "case_name": "Stub v. State",
            "case_name_short": "",
            "case_name_full": "",
            "judges": "",
            "precedential_status": "Published",
            "syllabus": "",
            "headnotes": "",
            "summary": "",
            "disposition": "",
            "procedural_history": "",
            "attorneys": "",
            "blocked": False,
            "date_filed_is_approximate": False,
            "courtlistener_id": None,
        }
        sync_opinion_cluster(row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-OC2"
        )
        stub_pk = stub.pk

        # Now sync the full docket
        docket_row = self._full_docket_row("SC-STUB-OC2")
        cl_id = sync_docket(docket_row)

        self.assertEqual(cl_id, stub_pk)
        stub.refresh_from_db()
        self.assertEqual(stub.case_name, "Full Case Name")
        self.assertEqual(stub.panel_str, "Robinson, C.J.")
        self.assertEqual(stub.source, DocketSources.SCRAPER)

    # -- opinion ---------------------------------------------------------------

    def test_opinion_creates_stub_docket(self):
        # First, create the stub + cluster so the opinion has a parent cluster
        cluster_row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OP",
            "date_filed": date(2024, 4, 1),
            "case_name": "Opinion Stub Case",
            "case_name_short": "",
            "case_name_full": "",
            "judges": "",
            "precedential_status": "Published",
            "syllabus": "",
            "headnotes": "",
            "summary": "",
            "disposition": "",
            "procedural_history": "",
            "attorneys": "",
            "blocked": False,
            "date_filed_is_approximate": False,
            "courtlistener_id": None,
        }
        sync_opinion_cluster(cluster_row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-OP"
        )
        self.assertEqual(stub.source, DocketSources.SCRAPER)

        # Now sync an opinion — it finds the stub docket + cluster
        opinion_row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OP",
            "cluster_date_filed": date(2024, 4, 1),
            "type": Opinion.LEAD,
            "author_str": "Judge Test",
            "per_curiam": False,
            "joined_by_str": "",
            "sha1": "stubsha",
            "page_count": 5,
            "download_url": "https://example.com/stub-opinion.pdf",
            "plain_text": "Stub opinion text.",
            "html": "",
            "extracted_by_ocr": False,
            "courtlistener_id": None,
        }
        cl_id = sync_opinion(opinion_row)

        opinion = Opinion.objects.get(pk=cl_id)
        self.assertEqual(opinion.cluster.docket_id, stub.pk)
        self.assertEqual(opinion.author_str, "Judge Test")

    def test_opinion_stub_updated_by_sync_docket(self):
        # Create stub via cluster, then opinion
        cluster_row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OP2",
            "date_filed": date(2024, 4, 1),
            "case_name": "Opinion Stub Case",
            "case_name_short": "",
            "case_name_full": "",
            "judges": "",
            "precedential_status": "Published",
            "syllabus": "",
            "headnotes": "",
            "summary": "",
            "disposition": "",
            "procedural_history": "",
            "attorneys": "",
            "blocked": False,
            "date_filed_is_approximate": False,
            "courtlistener_id": None,
        }
        sync_opinion_cluster(cluster_row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-OP2"
        )
        stub_pk = stub.pk

        # Full docket sync updates the stub
        docket_row = self._full_docket_row("SC-STUB-OP2")
        cl_id = sync_docket(docket_row)

        self.assertEqual(cl_id, stub_pk)
        stub.refresh_from_db()
        self.assertEqual(stub.case_name, "Full Case Name")

    # -- docket_entry ----------------------------------------------------------

    def test_docket_entry_creates_stub_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-DE",
            "document_uuid": "uuid-stub-001",
            "date_filed": date(2024, 5, 1),
            "time_filed": None,
            "entry_number": 1,
            "description": "Filed via stub",
            "courtlistener_id": None,
        }
        cl_id = sync_docket_entry(row)

        de = DocketEntry.objects.get(pk=cl_id)
        stub = de.docket
        self.assertEqual(stub.court_id, self.court.id)
        self.assertEqual(stub.docket_number, "SC-STUB-DE")
        self.assertEqual(stub.source, DocketSources.SCRAPER)
        # No case_name in docket_entry row → stub gets ""
        self.assertEqual(stub.case_name, "")

    def test_docket_entry_stub_updated_by_sync_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-DE2",
            "document_uuid": "uuid-stub-002",
            "date_filed": date(2024, 5, 1),
            "time_filed": None,
            "entry_number": 1,
            "description": "Filed via stub",
            "courtlistener_id": None,
        }
        sync_docket_entry(row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-DE2"
        )
        stub_pk = stub.pk

        docket_row = self._full_docket_row("SC-STUB-DE2")
        cl_id = sync_docket(docket_row)

        self.assertEqual(cl_id, stub_pk)
        stub.refresh_from_db()
        self.assertEqual(stub.case_name, "Full Case Name")
        self.assertEqual(stub.appeal_from_str, "Circuit Court")

    # -- originating_court_information -----------------------------------------

    def test_oci_creates_stub_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OCI",
            "lower_court_docket_number": "CV-2023-999",
            "court_reporter": "",
            "assigned_to_str": "",
            "ordering_judge_str": "",
            "date_filed": None,
            "date_disposed": None,
            "date_judgment": None,
            "date_judgment_eod": None,
            "date_filed_noa": None,
            "date_received_coa": None,
            "courtlistener_id": None,
        }
        cl_id = sync_originating_court_information(row)

        oci = OriginatingCourtInformation.objects.get(pk=cl_id)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-OCI"
        )
        self.assertEqual(stub.source, DocketSources.SCRAPER)
        self.assertEqual(stub.originating_court_information_id, oci.pk)

    def test_oci_stub_updated_by_sync_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-OCI2",
            "lower_court_docket_number": "CV-2023-999",
            "court_reporter": "",
            "assigned_to_str": "",
            "ordering_judge_str": "",
            "date_filed": None,
            "date_disposed": None,
            "date_judgment": None,
            "date_judgment_eod": None,
            "date_filed_noa": None,
            "date_received_coa": None,
            "courtlistener_id": None,
        }
        sync_originating_court_information(row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-OCI2"
        )
        stub_pk = stub.pk

        docket_row = self._full_docket_row("SC-STUB-OCI2")
        cl_id = sync_docket(docket_row)

        self.assertEqual(cl_id, stub_pk)
        stub.refresh_from_db()
        self.assertEqual(stub.case_name, "Full Case Name")

    # -- audio -----------------------------------------------------------------

    def test_audio_creates_stub_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-AU",
            "date_argued": date(2024, 6, 1),
            "case_name": "Audio Stub Case",
            "case_name_short": "",
            "case_name_full": "",
            "judges": "",
            "download_url": "https://example.com/stub-audio.mp3",
            "duration": 1800,
            "stt_status": Audio.STT_NEEDED,
            "blocked": False,
            "courtlistener_id": None,
        }
        cl_id = sync_audio(row)

        audio = Audio.objects.get(pk=cl_id)
        stub = audio.docket
        self.assertEqual(stub.court_id, self.court.id)
        self.assertEqual(stub.docket_number, "SC-STUB-AU")
        self.assertEqual(stub.source, DocketSources.SCRAPER)
        self.assertEqual(stub.case_name, "Audio Stub Case")

    def test_audio_stub_updated_by_sync_docket(self):
        row = {
            "court_id": self.court.id,
            "docket_number": "SC-STUB-AU2",
            "date_argued": date(2024, 6, 1),
            "case_name": "Audio Stub Case",
            "case_name_short": "",
            "case_name_full": "",
            "judges": "",
            "download_url": "https://example.com/stub-audio.mp3",
            "duration": 1800,
            "stt_status": Audio.STT_NEEDED,
            "blocked": False,
            "courtlistener_id": None,
        }
        sync_audio(row)
        stub = Docket.objects.get(
            court=self.court, docket_number="SC-STUB-AU2"
        )
        stub_pk = stub.pk

        docket_row = self._full_docket_row("SC-STUB-AU2")
        cl_id = sync_docket(docket_row)

        self.assertEqual(cl_id, stub_pk)
        stub.refresh_from_db()
        self.assertEqual(stub.case_name, "Full Case Name")
        self.assertEqual(stub.source, DocketSources.SCRAPER)
